# Generated by Django 5.2.17 on 2026-09-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='房型名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每晚价格')),
                ('capacity', models.PositiveIntegerField(verbose_name='可住人数')),
                ('area', models.PositiveIntegerField(verbose_name='面积（平方米）')),
                ('bed_type', models.CharField(max_length=100, verbose_name='床型说明')),
                ('window', models.BooleanField(default=True, verbose_name='是否有窗')),
                ('breakfast', models.BooleanField(default=False, verbose_name='是否含早餐')),
                ('description', models.TextField(verbose_name='房型描述')),
                ('cover_image', models.CharField(blank=True, default='', max_length=255, verbose_name='封面图片')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='总库存')),
                ('remaining_stock', models.PositiveIntegerField(default=0, verbose_name='剩余库存')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
                'db_table': 'room_type',
                'db_table_comment': '房间类型',
                'ordering': ('price', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True, verbose_name='房间号')),
                ('status', models.CharField(choices=[('vacant', '空闲'), ('occupied', '已入住'), ('cleaning', '清洁中'), ('maintenance', '维修中')], default='vacant', max_length=20, verbose_name='房间状态')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype', verbose_name='所属房型')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
                'db_table_comment': '房间信息',
                'ordering': ('room_number',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '房型评价',
                'verbose_name_plural': '房型评价',
                'db_table': 'review',
                'db_table_comment': '房型评价',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='入住日期')),
                ('end_date', models.DateField(verbose_name='退房日期')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总价')),
                ('contact_name', models.CharField(blank=True, default='', max_length=50, verbose_name='入住人姓名')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=11, verbose_name='联系电话')),
                ('id_card', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('payment_method', models.CharField(default='hang_charge', max_length=30, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('booked', '已预订'), ('checked_in', '已入住'), ('completed', '已完成'), ('cancelled', '已取消')], default='booked', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='预订用户')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room', verbose_name='分配房间')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '预订订单',
                'verbose_name_plural': '预订订单',
                'db_table': 'booking',
                'db_table_comment': '预订订单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='rooms.roomtype', verbose_name='收藏房型')),
            ],
            options={
                'verbose_name': '房型收藏',
                'verbose_name_plural': '房型收藏',
                'db_table': 'favorite',
                'db_table_comment': '房型收藏',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'room_type')},
            },
        ),
    ]
