# Generated by Django 5.2.17 on 2026-09-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(db_comment='AI 对话会话唯一编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('session_id', models.CharField(db_comment='前端与 LangGraph 共享的会话编号', max_length=100, unique=True, verbose_name='会话编号')),
                ('title', models.CharField(db_comment='根据用户首条消息生成的会话标题', max_length=120, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='会话创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='会话最近更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_comment='发起 AI 对话的系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 对话会话',
                'verbose_name_plural': 'AI 对话会话',
                'db_table': 'ai_chat_session',
                'db_table_comment': 'AI 对话会话',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(db_comment='AI 对话消息唯一编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI')], db_comment='消息发送方角色', max_length=20, verbose_name='消息角色')),
                ('kind', models.CharField(choices=[('text', '用户文本'), ('reply', 'AI 回复'), ('process', '执行过程')], db_comment='消息在对话流中的类型', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, db_comment='用户输入、AI 回复或过程摘要内容', default='', verbose_name='消息内容')),
                ('process_payload', models.JSONField(blank=True, db_comment='工具调用、工具结果等过程消息的结构化数据', default=dict, verbose_name='过程数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='消息创建时间', verbose_name='创建时间')),
                ('session', models.ForeignKey(db_comment='消息所属的 AI 对话会话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AiChat.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'AI 对话消息',
                'verbose_name_plural': 'AI 对话消息',
                'db_table': 'ai_chat_message',
                'db_table_comment': 'AI 对话消息',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
