import { adminRoles, bookingStatuses, feedbackStatuses, roomStatuses } from './options'

export const resourceConfigs = {
  users: {
    key: 'users',
    title: '用户管理',
    subtitle: '维护系统用户、管理员角色与账号状态',
    resource: 'users',
    createText: '新增用户',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'username', label: '用户名', minWidth: 130 },
      { prop: 'mobile', label: '手机号', minWidth: 130 },
      { prop: 'email', label: '邮箱', minWidth: 170 },
      { prop: 'role', label: '角色', type: 'role', width: 110 },
      { prop: 'is_active', label: '启用', type: 'boolean', width: 88 },
      { prop: 'date_joined', label: '注册时间', type: 'datetime', minWidth: 160 },
    ],
    fields: [
      { prop: 'username', label: '用户名', type: 'input', required: true },
      { prop: 'password', label: '密码', type: 'password' },
      { prop: 'mobile', label: '手机号', type: 'input', required: true },
      { prop: 'email', label: '邮箱', type: 'input' },
      { prop: 'first_name', label: '名', type: 'input' },
      { prop: 'last_name', label: '姓', type: 'input' },
      { prop: 'role', label: '角色', type: 'select', optionsKey: 'roles', default: 'user' },
      { prop: 'is_active', label: '启用状态', type: 'switch', default: true },
      { prop: 'is_staff', label: '后台员工', type: 'switch', default: false },
    ],
  },
  roomTypes: {
    key: 'room-types',
    title: '房型管理',
    subtitle: '维护房型价格、设施标签、库存与封面图片',
    resource: 'room-types',
    createText: '新增房型',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'cover_image', label: '图片', type: 'image', width: 110 },
      { prop: 'name', label: '房型名称', minWidth: 150 },
      { prop: 'price', label: '价格', type: 'money', width: 110 },
      { prop: 'capacity', label: '人数', width: 86 },
      { prop: 'bed_type', label: '床型', minWidth: 120 },
      { prop: 'total_stock', label: '总库存', width: 96 },
      { prop: 'remaining_stock', label: '剩余', width: 86 },
    ],
    fields: [
      { prop: 'name', label: '房型名称', type: 'input', required: true },
      { prop: 'price', label: '每晚价格', type: 'number', default: 0 },
      { prop: 'capacity', label: '容纳人数', type: 'number', default: 1 },
      { prop: 'area', label: '面积', type: 'number', default: 30 },
      { prop: 'bed_type', label: '床型说明', type: 'input' },
      { prop: 'window', label: '是否有窗', type: 'switch', default: true },
      { prop: 'breakfast', label: '是否含早', type: 'switch', default: false },
      { prop: 'cover_image_upload', label: '封面图片', type: 'file', accept: 'image/*' },
      { prop: 'total_stock', label: '总库存', type: 'number', default: 0 },
      { prop: 'remaining_stock', label: '剩余库存', type: 'number', default: 0 },
      { prop: 'description', label: '房型描述', type: 'textarea' },
    ],
  },
  rooms: {
    key: 'rooms',
    title: '房间管理',
    subtitle: '维护具体房间号、所属房型、楼层与客房状态',
    resource: 'rooms',
    createText: '新增房间',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'room_number', label: '房间号', width: 110 },
      { prop: 'room_type_name', label: '所属房型', minWidth: 150 },
      { prop: 'floor', label: '楼层', width: 86 },
      { prop: 'status_display', label: '状态', width: 110 },
    ],
    fields: [
      { prop: 'room_number', label: '房间号', type: 'input', required: true },
      { prop: 'room_type', label: '所属房型', type: 'select', optionsKey: 'roomTypes', required: true },
      { prop: 'floor', label: '楼层', type: 'number', default: 1 },
      { prop: 'status', label: '房间状态', type: 'select', optionsKey: 'roomStatuses', default: 'vacant' },
    ],
  },
  bookings: {
    key: 'bookings',
    title: '订单管理',
    subtitle: '维护用户预订订单、入住日期、分配房间和订单状态',
    resource: 'bookings',
    createText: '新增订单',
    columns: [
      { prop: 'id', label: '订单号', width: 88 },
      { prop: 'username', label: '用户', minWidth: 110 },
      { prop: 'room_type_name', label: '房型', minWidth: 150 },
      { prop: 'room_number', label: '房间', width: 90 },
      { prop: 'total_price', label: '总价', type: 'money', width: 110 },
      { prop: 'status_display', label: '状态', width: 110 },
      { prop: 'created_at', label: '创建时间', type: 'datetime', minWidth: 160 },
    ],
    fields: [
      { prop: 'user', label: '预订用户', type: 'select', optionsKey: 'users', required: true },
      { prop: 'room_type', label: '房型', type: 'select', optionsKey: 'roomTypes', required: true },
      { prop: 'room', label: '分配房间', type: 'select', optionsKey: 'rooms' },
      { prop: 'start_date', label: '入住日期', type: 'date', required: true },
      { prop: 'end_date', label: '退房日期', type: 'date', required: true },
      { prop: 'total_price', label: '订单总价', type: 'number', default: 0 },
      { prop: 'status', label: '订单状态', type: 'select', optionsKey: 'bookingStatuses', default: 'booked' },
      { prop: 'contact_name', label: '入住人', type: 'input' },
      { prop: 'contact_phone', label: '联系电话', type: 'input' },
      { prop: 'id_card', label: '身份证号', type: 'input' },
      { prop: 'payment_method', label: '支付方式', type: 'input', default: 'hang_charge' },
    ],
  },
  feedbacks: {
    key: 'feedbacks',
    title: '留言管理',
    subtitle: '处理用户留言反馈、联系方式与管理员回复',
    resource: 'feedbacks',
    createText: '新增留言',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'username', label: '用户', minWidth: 110 },
      { prop: 'title', label: '标题', minWidth: 170 },
      { prop: 'status_display', label: '状态', width: 110 },
      { prop: 'reply_content', label: '回复内容', minWidth: 220 },
      { prop: 'created_at', label: '提交时间', type: 'datetime', minWidth: 160 },
    ],
    fields: [
      { prop: 'user', label: '用户', type: 'select', optionsKey: 'users', required: true },
      { prop: 'title', label: '标题', type: 'input', required: true },
      { prop: 'content', label: '留言内容', type: 'textarea', required: true },
      { prop: 'contact', label: '联系方式', type: 'input' },
      { prop: 'status', label: '处理状态', type: 'select', optionsKey: 'feedbackStatuses', default: 'pending' },
      { prop: 'reply_content', label: '回复内容', type: 'textarea' },
    ],
  },
  reviews: {
    key: 'reviews',
    title: '评论管理',
    subtitle: '维护用户对房型的评分和文字评价',
    resource: 'reviews',
    createText: '新增评论',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'username', label: '用户', minWidth: 110 },
      { prop: 'room_type_name', label: '房型', minWidth: 150 },
      { prop: 'rating', label: '评分', width: 88 },
      { prop: 'content', label: '评论内容', minWidth: 260 },
      { prop: 'created_at', label: '评论时间', type: 'datetime', minWidth: 160 },
    ],
    fields: [
      { prop: 'user', label: '用户', type: 'select', optionsKey: 'users', required: true },
      { prop: 'room_type', label: '房型', type: 'select', optionsKey: 'roomTypes', required: true },
      { prop: 'rating', label: '评分', type: 'number', default: 5 },
      { prop: 'content', label: '评论内容', type: 'textarea', required: true },
    ],
  },
  favorites: {
    key: 'favorites',
    title: '收藏管理',
    subtitle: '维护用户收藏的房型记录',
    resource: 'favorites',
    createText: '新增收藏',
    columns: [
      { prop: 'id', label: '编号', width: 78 },
      { prop: 'username', label: '用户', minWidth: 120 },
      { prop: 'room_type_name', label: '收藏房型', minWidth: 180 },
      { prop: 'created_at', label: '收藏时间', type: 'datetime', minWidth: 160 },
    ],
    fields: [
      { prop: 'user', label: '用户', type: 'select', optionsKey: 'users', required: true },
      { prop: 'room_type', label: '房型', type: 'select', optionsKey: 'roomTypes', required: true },
    ],
  },
}

export const baseSelectOptions = {
  roles: adminRoles,
  roomStatuses,
  bookingStatuses,
  feedbackStatuses,
}
