# Generated by Django 5.2.17 on 2026-09-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='反馈标题')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待回复'), ('replied', '已回复'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reply_content', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '用户留言反馈',
                'verbose_name_plural': '用户留言反馈',
                'db_table': 'feedback',
                'db_table_comment': '用户留言反馈',
                'ordering': ('-created_at',),
            },
        ),
    ]
